FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.50.0
FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.50.0
FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.50.0
FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.50.0
## 不知道干嘛的 先留着  LABEL MAINTAINER=master@weiyigeeek.top BUILDTYPE=Aliyun